# Machine Learning Lab1

# Divyansh 21BAI1240


##### Importing Required Libraries:

In [3]:
import numpy as np

### 1.	How to create an empty and a full NumPy array?

In [ ]:
# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 64, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array
[[64 64 64]
 [64 64 64]
 [64 64 64]]


### 2.	Create a Numpy array filled with all zeros

In [4]:
zeros_arr = np.zeros(6,int)
print(zeros_arr)

[0 0 0 0 0 0]


### 3.	Create a Numpy array filled with all ones

In [5]:
ones_arr = np.ones(6,int)
print(ones_arr)

[1 1 1 1 1 1]


### 4.	Check whether a Numpy array contains a specified row

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_to_find = [4, 5, 6]

if np.any(np.all(arr == row_to_find, axis=1)):
    print("The row is present in the array")
else:
    print("The row is not present in the array")

The row is present in the array


### 5.	How to Remove rows in Numpy array that contains non-numeric values?

In [ ]:
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9],
                [10, np.nan, np.nan]])

nan_rows = np.isnan(arr).any(axis=1)
clean_arr = arr[~nan_rows]
print(clean_arr)


[[ 1.  2.  3.]
 [ 7.  8.  9.]]


### 6.	Remove single-dimensional entries from the shape of an array

In [ ]:
arr = np.array([[[1, 2, 3]],
                [[4, 5, 6]]])

print("Original shape:", arr.shape)
squeezed_arr = np.squeeze(arr)
print("Squeezed shape:", squeezed_arr.shape)

Original shape: (2, 1, 3)
Squeezed shape: (2, 3)


### 7.	Find the number of occurrences of a sequence in a NumPy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3])
seq = "1, 2, 3"
output = repr(arr).count(str(seq))
print(output)

3


### 8.	Find the most frequent value in a NumPy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 1, 2, 3, 1, 1])
counts = np.bincount(arr.astype('int64'))
most_frequent_value = np.argmax(counts)
print("Most frequent value:", most_frequent_value)

Most frequent value: 1


### 9.	Combining a one and a two-dimensional NumPy Array

In [ ]:
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


### 10.	How to build an array of all combinations of two NumPy arrays?

In [ ]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
print("Array-1")
print(array_1)
print("\nArray-2")
print(array_2)
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
print("\nCombine array:")
print(comb_array)

Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]
